# Generated by Django 4.1.1 on 2022-09-07 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_tag_user_alter_userprofile_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='tags',
            field=models.ManyToManyField(null=True, to='core.tag'),
        ),
    ]
