# Generated by Django 4.1.1 on 2022-09-15 21:42

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_userprofile_profile_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.blog')),
                ('user', models.ForeignKey(on_delete=models.SET(core.models.get_anonymous_user), to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply', models.TextField()),
                ('comment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.usercomment')),
                ('user', models.ForeignKey(on_delete=models.SET(core.models.get_anonymous_user), to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
