# Generated by Django 4.1.1 on 2022-09-16 00:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_usercomment_userreply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercomment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.blog'),
        ),
        migrations.AlterField(
            model_name='userreply',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.usercomment'),
        ),
    ]
