# Generated by Django 4.1.1 on 2022-10-03 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0011_blog_created_on_usercomment_created_on_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercomment',
            old_name='comment',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='usercomment',
            name='post',
        ),
        migrations.AddField(
            model_name='usercomment',
            name='content_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usercomment',
            name='object_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='UserReply',
        ),
    ]
